USE Storehouse
GO

CREATE TABLE dbo.Files (
	Id INT IDENTITY(1,1),
	DateCreated DATETIME,
	[Path] NVARCHAR(MAX),
	Name NVARCHAR(200),
	Extension CHAR(3),
	Data VARBINARY(MAX)
)
WITH (DATA_COMPRESSION = PAGE)
GO

CREATE UNIQUE CLUSTERED INDEX CIX_Dbo_Files_Id ON dbo.Files(Id)
WITH (DATA_COMPRESSION = PAGE)
ON [FAST]
GO



